apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - protocol: TCP
    targetPort: 27017
    port: 27017
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: db
spec:
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: mongo
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 90
