apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nodejs
        image: dawker/docknode:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 9090
    port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: backend
spec:
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: node
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 90
